/**
 * q(n, m) and p(n) via Euler's pentagonal number recurrence - a direct
 * BigInt port of Version3/partition_rank.py's _build_q_table/_p_sequence.
 * Keep this file's logic in lockstep with that one; web/test/vectors/
 * (generated by Version3/export_test_vectors.py) is what proves they
 * still agree.
 */

const qTableCache = new Map<number, bigint[][]>();

export function buildQTable(nMax: number): bigint[][] {
  const table: bigint[][] = Array.from({ length: nMax + 1 }, () =>
    new Array<bigint>(nMax + 1).fill(0n)
  );
  for (let m = 0; m <= nMax; m++) {
    table[0]![m] = 1n;
  }
  for (let m = 1; m <= nMax; m++) {
    for (let n = 1; n <= nMax; n++) {
      const withoutM = table[n]![m - 1]!;
      const withM = n >= m ? table[n - m]![m]! : 0n;
      table[n]![m] = withoutM + withM;
    }
  }
  return table;
}

/** Cached q(n, m) table for 0 <= n, m <= nMax. */
export function getQTable(nMax: number): bigint[][] {
  let table = qTableCache.get(nMax);
  if (!table) {
    table = buildQTable(nMax);
    qTableCache.set(nMax, table);
  }
  return table;
}

/** Number of partitions of n into parts each at most m. */
export function q(n: number, m: number): bigint {
  if (n < 0) return 0n;
  if (m <= 0) return n === 0 ? 1n : 0n;
  const table = getQTable(Math.max(n, m));
  return table[n]![m]!;
}

/** p(N): the total number of partitions of N. */
export function partitionsCount(N: number): bigint {
  if (N < 0) throw new Error('N must be non-negative');
  if (N === 0) return 1n;
  return q(N, N);
}

/**
 * p(0..nMax) via the pentagonal recurrence - O(n^1.5), far cheaper than
 * building the full q(n, m) table when only the 1-D total-count sequence
 * is needed (minN's search).
 */
export function pSequence(nMax: number): bigint[] {
  const p: bigint[] = new Array(nMax + 1).fill(0n);
  p[0] = 1n;
  for (let i = 1; i <= nMax; i++) {
    let total = 0n;
    let k = 1;
    for (;;) {
      const g1 = (k * (3 * k - 1)) / 2;
      const g2 = (k * (3 * k + 1)) / 2;
      if (g1 > i && g2 > i) break;
      const sign = k % 2 !== 0 ? 1n : -1n;
      if (g1 <= i) total += sign * p[i - g1]!;
      if (g2 <= i) total += sign * p[i - g2]!;
      k += 1;
    }
    p[i] = total;
  }
  return p;
}

/** Smallest N such that p(N) >= space. */
export function minN(space: bigint): number {
  if (space <= 1n) return 0;

  let nMax = 16;
  let p = pSequence(nMax);
  while (p[nMax]! < space) {
    nMax *= 2;
    p = pSequence(nMax);
  }

  let lo = 0;
  let hi = nMax;
  while (lo < hi) {
    const mid = Math.floor((lo + hi) / 2);
    if (p[mid]! >= space) {
      hi = mid;
    } else {
      lo = mid + 1;
    }
  }
  return lo;
}
